# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Security_Question/form_Secr_Question.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Security_QuestionR(object):
    def setupUi(self, Form_Security_QuestionR):
        Form_Security_QuestionR.setObjectName("Form_Security_QuestionR")
        Form_Security_QuestionR.resize(892, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_Security_QuestionR.setWindowIcon(icon)
        Form_Security_QuestionR.setStyleSheet("background-color: #ebebea;")
        self.label_6 = QtWidgets.QLabel(Form_Security_QuestionR)
        self.label_6.setGeometry(QtCore.QRect(0, 80, 892, 425))
        self.label_6.setStyleSheet("background-color: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Images/Aset/Shadow_blue.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(Form_Security_QuestionR)
        self.label_5.setGeometry(QtCore.QRect(260, -40, 341, 221))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Images/Aset/Logo-removebg.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Form_Security_QuestionR)
        self.label.setGeometry(QtCore.QRect(280, 110, 311, 43))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: transparent;\n"
"font-size: 28px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Form_Security_QuestionR)
        self.label_7.setGeometry(QtCore.QRect(270, 180, 75, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #666666;\n"
"background-color: transparent;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.txt_answer = QtWidgets.QLineEdit(Form_Security_QuestionR)
        self.txt_answer.setGeometry(QtCore.QRect(270, 310, 321, 29))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.txt_answer.setFont(font)
        self.txt_answer.setStyleSheet("border : 1px solid transparent;\n"
"border-radius : 9px;\n"
"background-color: white;\n"
"color: #666666;")
        self.txt_answer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_answer.setObjectName("txt_answer")
        self.txt_Quest = QtWidgets.QTextEdit(Form_Security_QuestionR)
        self.txt_Quest.setGeometry(QtCore.QRect(270, 200, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.txt_Quest.setFont(font)
        self.txt_Quest.setStyleSheet("border : 1px solid transparent;\n"
"border-radius : 9px;\n"
"background-color: white;\n"
"color: #666666;")
        self.txt_Quest.setReadOnly(True)
        self.txt_Quest.setObjectName("txt_Quest")
        self.label_8 = QtWidgets.QLabel(Form_Security_QuestionR)
        self.label_8.setGeometry(QtCore.QRect(260, 290, 69, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #666666;\n"
"background-color: transparent;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(Form_Security_QuestionR)
        self.label_2.setGeometry(QtCore.QRect(270, 350, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #a6a6a6;\n"
"background-color: transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_Security_QuestionR)
        self.label_3.setGeometry(QtCore.QRect(270, 361, 319, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #a6a6a6;\n"
"background-color:transparent;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.btn_identify = QtWidgets.QPushButton(Form_Security_QuestionR)
        self.btn_identify.setGeometry(QtCore.QRect(280, 430, 298, 35))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_identify.setFont(font)
        self.btn_identify.setStyleSheet("border: 1px solid #5ca3ff;\n"
"border-radius: 9px;\n"
"background-color: #5ca3ff;\n"
"color: #ffffff;")
        self.btn_identify.setObjectName("btn_identify")
        self.btnBack = QtWidgets.QPushButton(Form_Security_QuestionR)
        self.btnBack.setGeometry(QtCore.QRect(39, 25, 28, 28))
        self.btnBack.setStyleSheet("background-color: transparent;")
        self.btnBack.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/Aset/btn_back_noBG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon1)
        self.btnBack.setIconSize(QtCore.QSize(28, 28))
        self.btnBack.setObjectName("btnBack")
        self.label_6.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.txt_answer.raise_()
        self.txt_Quest.raise_()
        self.label_8.raise_()
        self.label_3.raise_()
        self.btn_identify.raise_()
        self.label_2.raise_()
        self.btnBack.raise_()

        self.retranslateUi(Form_Security_QuestionR)
        QtCore.QMetaObject.connectSlotsByName(Form_Security_QuestionR)

    def retranslateUi(self, Form_Security_QuestionR):
        _translate = QtCore.QCoreApplication.translate
        Form_Security_QuestionR.setWindowTitle(_translate("Form_Security_QuestionR", "SECURITY QUESTION"))
        self.label.setText(_translate("Form_Security_QuestionR", "Security Question"))
        self.label_7.setText(_translate("Form_Security_QuestionR", "Pertanyaan"))
        self.label_8.setText(_translate("Form_Security_QuestionR", "Jawab"))
        self.label_2.setText(_translate("Form_Security_QuestionR", "Identifikasi bahwa anda adalah pemilik akun yang sebenarnya."))
        self.label_3.setText(_translate("Form_Security_QuestionR", "________________________________________________________________"))
        self.btn_identify.setText(_translate("Form_Security_QuestionR", "Identifikasi"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Security_QuestionR = QtWidgets.QWidget()
    ui = Ui_Form_Security_QuestionR()
    ui.setupUi(Form_Security_QuestionR)
    Form_Security_QuestionR.show()
    sys.exit(app.exec_())
