# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Login/form_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(892, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_login.setWindowIcon(icon)
        Form_login.setStyleSheet("background-color: #ebebea;")
        self.label = QtWidgets.QLabel(Form_login)
        self.label.setGeometry(QtCore.QRect(390, 100, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txt_usernames = QtWidgets.QLineEdit(Form_login)
        self.txt_usernames.setGeometry(QtCore.QRect(310, 210, 261, 29))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.txt_usernames.setFont(font)
        self.txt_usernames.setStyleSheet("border : 1px solid transparent;\n"
"border-radius : 9px;\n"
"background-color: white;\n"
"color:#666666;")
        self.txt_usernames.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_usernames.setObjectName("txt_usernames")
        self.txt_passwords = QtWidgets.QLineEdit(Form_login)
        self.txt_passwords.setGeometry(QtCore.QRect(310, 280, 261, 29))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.txt_passwords.setFont(font)
        self.txt_passwords.setStyleSheet("border : 1px solid transparent;\n"
"border-radius : 9px;\n"
"background-color: white;\n"
"color:#666666;")
        self.txt_passwords.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_passwords.setObjectName("txt_passwords")
        self.btn_Login = QtWidgets.QPushButton(Form_login)
        self.btn_Login.setGeometry(QtCore.QRect(310, 370, 261, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Login.setFont(font)
        self.btn_Login.setStyleSheet("border: 1px solid #5ca3ff;\n"
"border-radius: 9px;\n"
"background-color: #5ca3ff;\n"
"color: #ffffff;")
        self.btn_Login.setObjectName("btn_Login")
        self.btn_to_Regist = QtWidgets.QPushButton(Form_login)
        self.btn_to_Regist.setGeometry(QtCore.QRect(310, 430, 261, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_to_Regist.setFont(font)
        self.btn_to_Regist.setStyleSheet("border: 1px solid transparent;\n"
"border-radius: 9px;\n"
"background-color: #ffffff;\n"
"color: gray;")
        self.btn_to_Regist.setObjectName("btn_to_Regist")
        self.label_3 = QtWidgets.QLabel(Form_login)
        self.label_3.setGeometry(QtCore.QRect(460, 400, 101, 20))
        self.label_3.setStyleSheet("background-color : transparent;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_login)
        self.label_4.setGeometry(QtCore.QRect(420, 400, 32, 27))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: transparent;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_login)
        self.label_5.setGeometry(QtCore.QRect(260, -40, 341, 221))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Images/Aset/Logo-removebg.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form_login)
        self.label_6.setGeometry(QtCore.QRect(0, 80, 892, 425))
        self.label_6.setStyleSheet("background-color: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Images/Aset/Shadow_blue.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form_login)
        self.label_7.setGeometry(QtCore.QRect(310, 190, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #666666;\n"
"background-color: transparent;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form_login)
        self.label_8.setGeometry(QtCore.QRect(310, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #666666;\n"
"background-color:transparent;")
        self.label_8.setObjectName("label_8")
        self.chk_show_Pw = QtWidgets.QCheckBox(Form_login)
        self.chk_show_Pw.setGeometry(QtCore.QRect(460, 308, 111, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chk_show_Pw.setFont(font)
        self.chk_show_Pw.setStyleSheet("background-color: transparent;\n"
"color: #666666;")
        self.chk_show_Pw.setIconSize(QtCore.QSize(16, 16))
        self.chk_show_Pw.setCheckable(True)
        self.chk_show_Pw.setChecked(False)
        self.chk_show_Pw.setObjectName("chk_show_Pw")
        self.label_9 = QtWidgets.QLabel(Form_login)
        self.label_9.setGeometry(QtCore.QRect(320, 400, 101, 20))
        self.label_9.setStyleSheet("background-color : transparent;\n"
"")
        self.label_9.setObjectName("label_9")
        self.btnResetpw = QtWidgets.QPushButton(Form_login)
        self.btnResetpw.setGeometry(QtCore.QRect(720, 430, 101, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.btnResetpw.setFont(font)
        self.btnResetpw.setStyleSheet("background-color: transparent;\n"
"color: #2d48b8;")
        self.btnResetpw.setObjectName("btnResetpw")
        self.label_6.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.txt_usernames.raise_()
        self.txt_passwords.raise_()
        self.btn_to_Regist.raise_()
        self.btn_Login.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.chk_show_Pw.raise_()
        self.label_9.raise_()
        self.btnResetpw.raise_()

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "LOGIN"))
        self.label.setText(_translate("Form_login", "Login"))
        self.txt_usernames.setPlaceholderText(_translate("Form_login", "Masukkan Username"))
        self.txt_passwords.setPlaceholderText(_translate("Form_login", "Masukkan Password"))
        self.btn_Login.setText(_translate("Form_login", "Login"))
        self.btn_to_Regist.setText(_translate("Form_login", "Register"))
        self.label_3.setText(_translate("Form_login", "_________________"))
        self.label_4.setText(_translate("Form_login", "or"))
        self.label_7.setText(_translate("Form_login", " Username"))
        self.label_8.setText(_translate("Form_login", " Password"))
        self.chk_show_Pw.setText(_translate("Form_login", "Show Password"))
        self.label_9.setText(_translate("Form_login", "________________"))
        self.btnResetpw.setText(_translate("Form_login", "Reset password?"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_login = QtWidgets.QWidget()
    ui = Ui_Form_login()
    ui.setupUi(Form_login)
    Form_login.show()
    sys.exit(app.exec_())
