# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_reset_pass/Resetpasss.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_resetPassword(object):
    def setupUi(self, form_resetPassword):
        form_resetPassword.setObjectName("form_resetPassword")
        form_resetPassword.resize(892, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        form_resetPassword.setWindowIcon(icon)
        form_resetPassword.setStyleSheet("background-color: #ebebea;")
        self.label = QtWidgets.QLabel(form_resetPassword)
        self.label.setGeometry(QtCore.QRect(321, 118, 251, 47))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(form_resetPassword)
        self.label_2.setGeometry(QtCore.QRect(260, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color : #a6a6a6;")
        self.label_2.setObjectName("label_2")
        self.txtNew_Pass = QtWidgets.QLineEdit(form_resetPassword)
        self.txtNew_Pass.setGeometry(QtCore.QRect(252, 247, 391, 30))
        self.txtNew_Pass.setStyleSheet("border : 1px solid transparent;\n"
"border-radius : 11px;\n"
"background-color: white;\n"
"color: #666666;")
        self.txtNew_Pass.setObjectName("txtNew_Pass")
        self.label_3 = QtWidgets.QLabel(form_resetPassword)
        self.label_3.setGeometry(QtCore.QRect(260, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : #a6a6a6;\n"
"background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(form_resetPassword)
        self.label_4.setGeometry(QtCore.QRect(260, 291, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color : #a6a6a6;\n"
"background-color: transparent;")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.btnReset = QtWidgets.QPushButton(form_resetPassword)
        self.btnReset.setGeometry(QtCore.QRect(310, 409, 271, 35))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnReset.setFont(font)
        self.btnReset.setStyleSheet("border-radius: 14px;\n"
"background-color: #5ca2ff;\n"
"color: #ffffff;")
        self.btnReset.setObjectName("btnReset")
        self.btn_back = QtWidgets.QPushButton(form_resetPassword)
        self.btn_back.setGeometry(QtCore.QRect(39, 25, 28, 28))
        self.btn_back.setStyleSheet("background-color:transparent;")
        self.btn_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/Aset/btn_back_noBG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon1)
        self.btn_back.setIconSize(QtCore.QSize(28, 28))
        self.btn_back.setObjectName("btn_back")
        self.Logo_apk = QtWidgets.QLabel(form_resetPassword)
        self.Logo_apk.setGeometry(QtCore.QRect(270, -30, 341, 221))
        self.Logo_apk.setStyleSheet("background-color: transparent;")
        self.Logo_apk.setText("")
        self.Logo_apk.setPixmap(QtGui.QPixmap(":/Images/Aset/Logo-removebg.png"))
        self.Logo_apk.setScaledContents(True)
        self.Logo_apk.setObjectName("Logo_apk")
        self.shadow_blue = QtWidgets.QLabel(form_resetPassword)
        self.shadow_blue.setGeometry(QtCore.QRect(0, 75, 892, 425))
        self.shadow_blue.setStyleSheet("background-color: transparent;")
        self.shadow_blue.setText("")
        self.shadow_blue.setPixmap(QtGui.QPixmap(":/Images/Aset/Shadow_blue.jpg"))
        self.shadow_blue.setScaledContents(True)
        self.shadow_blue.setObjectName("shadow_blue")
        self.shadow_blue.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.txtNew_Pass.raise_()
        self.label_3.raise_()
        self.btnReset.raise_()
        self.btn_back.raise_()
        self.Logo_apk.raise_()

        self.retranslateUi(form_resetPassword)
        QtCore.QMetaObject.connectSlotsByName(form_resetPassword)

    def retranslateUi(self, form_resetPassword):
        _translate = QtCore.QCoreApplication.translate
        form_resetPassword.setWindowTitle(_translate("form_resetPassword", "RESET PASSWORD"))
        self.label.setText(_translate("form_resetPassword", "Reset Password"))
        self.label_2.setText(_translate("form_resetPassword", "Password Baru "))
        self.label_3.setText(_translate("form_resetPassword", "Catatan : "))
        self.label_4.setText(_translate("form_resetPassword", "Password setidaknya memuat 8 - 16 Karakter termasuk simbol seperti (&$#@%=)."))
        self.btnReset.setText(_translate("form_resetPassword", "Reset"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_resetPassword = QtWidgets.QWidget()
    ui = Ui_form_resetPassword()
    ui.setupUi(form_resetPassword)
    form_resetPassword.show()
    sys.exit(app.exec_())
