# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_buat_SecurityQuestion/form_Secr_Question.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_buat_scr_question(object):
    def setupUi(self, form_buat_scr_question):
        form_buat_scr_question.setObjectName("form_buat_scr_question")
        form_buat_scr_question.resize(892, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        form_buat_scr_question.setWindowIcon(icon)
        form_buat_scr_question.setStyleSheet("background-color: #ebebea;")
        self.label_6 = QtWidgets.QLabel(form_buat_scr_question)
        self.label_6.setGeometry(QtCore.QRect(0, 80, 892, 425))
        self.label_6.setStyleSheet("background-color: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Images/Aset/Shadow_blue.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.logo_img = QtWidgets.QLabel(form_buat_scr_question)
        self.logo_img.setGeometry(QtCore.QRect(260, -40, 341, 221))
        self.logo_img.setText("")
        self.logo_img.setPixmap(QtGui.QPixmap(":/Images/Aset/Logo-removebg.png"))
        self.logo_img.setScaledContents(True)
        self.logo_img.setObjectName("logo_img")
        self.label = QtWidgets.QLabel(form_buat_scr_question)
        self.label.setGeometry(QtCore.QRect(280, 110, 311, 43))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: transparent;\n"
"font-size: 28px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(form_buat_scr_question)
        self.label_7.setGeometry(QtCore.QRect(270, 180, 75, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #666666;\n"
"background-color: transparent;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.txt_answer = QtWidgets.QLineEdit(form_buat_scr_question)
        self.txt_answer.setGeometry(QtCore.QRect(270, 310, 321, 29))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.txt_answer.setFont(font)
        self.txt_answer.setStyleSheet("border : 1px solid transparent;\n"
"border-radius : 9px;\n"
"background-color: white;\n"
"color: #666666;")
        self.txt_answer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_answer.setObjectName("txt_answer")
        self.txt_Quest = QtWidgets.QTextEdit(form_buat_scr_question)
        self.txt_Quest.setGeometry(QtCore.QRect(270, 200, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.txt_Quest.setFont(font)
        self.txt_Quest.setStyleSheet("border : 1px solid transparent;\n"
"border-radius : 9px;\n"
"background-color: white;\n"
"color: #666666;")
        self.txt_Quest.setReadOnly(True)
        self.txt_Quest.setObjectName("txt_Quest")
        self.label_8 = QtWidgets.QLabel(form_buat_scr_question)
        self.label_8.setGeometry(QtCore.QRect(260, 290, 69, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #666666;\n"
"background-color: transparent;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(form_buat_scr_question)
        self.label_2.setGeometry(QtCore.QRect(270, 349, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #a6a6a6;\n"
"background-color: transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(form_buat_scr_question)
        self.label_3.setGeometry(QtCore.QRect(272, 341, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #a6a6a6;\n"
"background-color:transparent;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.btn_identify = QtWidgets.QPushButton(form_buat_scr_question)
        self.btn_identify.setGeometry(QtCore.QRect(280, 430, 298, 35))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_identify.setFont(font)
        self.btn_identify.setStyleSheet("border: 1px solid #5ca3ff;\n"
"border-radius: 9px;\n"
"background-color: #5ca3ff;\n"
"color: #ffffff;")
        self.btn_identify.setObjectName("btn_identify")
        self.btn_back = QtWidgets.QPushButton(form_buat_scr_question)
        self.btn_back.setGeometry(QtCore.QRect(39, 25, 28, 28))
        self.btn_back.setStyleSheet("background-color: transparent;")
        self.btn_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/Aset/btn_back_noBG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon1)
        self.btn_back.setIconSize(QtCore.QSize(28, 28))
        self.btn_back.setObjectName("btn_back")
        self.label_6.raise_()
        self.logo_img.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.txt_answer.raise_()
        self.txt_Quest.raise_()
        self.label_8.raise_()
        self.label_3.raise_()
        self.btn_identify.raise_()
        self.label_2.raise_()
        self.btn_back.raise_()

        self.retranslateUi(form_buat_scr_question)
        QtCore.QMetaObject.connectSlotsByName(form_buat_scr_question)

    def retranslateUi(self, form_buat_scr_question):
        _translate = QtCore.QCoreApplication.translate
        form_buat_scr_question.setWindowTitle(_translate("form_buat_scr_question", "SECURITY QUESTION"))
        self.label.setText(_translate("form_buat_scr_question", "Security Question"))
        self.label_7.setText(_translate("form_buat_scr_question", "Pertanyaan"))
        self.txt_answer.setPlaceholderText(_translate("form_buat_scr_question", "Masukkan Jawaban"))
        self.label_8.setText(_translate("form_buat_scr_question", "Jawab"))
        self.label_2.setText(_translate("form_buat_scr_question", "Catatan:\n"
"Security question digunakan untuk mengidentifikasi pengguna, ketika pengguna lupa password akun saat login."))
        self.label_3.setText(_translate("form_buat_scr_question", "_________"))
        self.btn_identify.setText(_translate("form_buat_scr_question", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_buat_scr_question = QtWidgets.QWidget()
    ui = Ui_form_buat_scr_question()
    ui.setupUi(form_buat_scr_question)
    form_buat_scr_question.show()
    sys.exit(app.exec_())
