# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageBox_Anywhere/Empty_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Empty(object):
    def setupUi(self, Form_Empty):
        Form_Empty.setObjectName("Form_Empty")
        Form_Empty.resize(892, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_Empty.setWindowIcon(icon)
        Form_Empty.setStyleSheet("background-color: #ebebea;")

        self.retranslateUi(Form_Empty)
        QtCore.QMetaObject.connectSlotsByName(Form_Empty)

    def retranslateUi(self, Form_Empty):
        _translate = QtCore.QCoreApplication.translate
        Form_Empty.setWindowTitle(_translate("Form_Empty", "Pesan"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Empty = QtWidgets.QWidget()
    ui = Ui_Form_Empty()
    ui.setupUi(Form_Empty)
    Form_Empty.show()
    sys.exit(app.exec_())
