# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageBox_Anywhere/msg_login_skss.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msg_box(object):
    def setupUi(self, msg_login_skss):
        msg_login_skss.setObjectName("msg_login_skss")
        msg_login_skss.resize(412, 230)
        msg_login_skss.setWindowTitle("Pesan")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msg_login_skss.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(msg_login_skss)
        self.label.setGeometry(QtCore.QRect(0, 0, 412, 31))
        self.label.setStyleSheet("background-color: rgb(0, 53, 81);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(msg_login_skss)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 412, 241))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.LblJenisMsg = QtWidgets.QLabel(msg_login_skss)
        self.LblJenisMsg.setGeometry(QtCore.QRect(10, 3, 200, 21))
        font = QtGui.QFont()
        font.setFamily("Montaser Arabic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LblJenisMsg.setFont(font)
        self.LblJenisMsg.setStyleSheet("font-family:Montaser Arabic;\n"
"color:#ffffff;\n"
"font-weight: bold;\n"
"")
        self.LblJenisMsg.setObjectName("LblJenisMsg")
        self.LblKonten_isi = QtWidgets.QLabel(msg_login_skss)
        self.LblKonten_isi.setGeometry(QtCore.QRect(14, 38, 385, 180))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.LblKonten_isi.setFont(font)
        self.LblKonten_isi.setStyleSheet("color:#a6a6a6;")
        self.LblKonten_isi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblKonten_isi.setWordWrap(True)
        self.LblKonten_isi.setObjectName("LblKonten_isi")

        self.retranslateUi(msg_login_skss)
        QtCore.QMetaObject.connectSlotsByName(msg_login_skss)

    def retranslateUi(self, msg_login_skss):
        _translate = QtCore.QCoreApplication.translate
        self.LblJenisMsg.setText(_translate("msg_login_skss", "Informasi!"))
        self.LblKonten_isi.setText(_translate("msg_login_skss", "Login berhasil!\n"
"Selamat datang username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    msg_login_skss = QtWidgets.QDialog()
    ui = Ui_msg_box()
    ui.setupUi(msg_login_skss)
    msg_login_skss.show()
    sys.exit(app.exec_())
