# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageBox_Anywhere/msgWith_btnYaTdk.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msgBox_YaTdk(object):
    def setupUi(self, msgBox_ok):
        msgBox_ok.setObjectName("msgBox_ok")
        msgBox_ok.resize(412, 230)
        msgBox_ok.setWindowTitle("Pesan")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msgBox_ok.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(msgBox_ok)
        self.label.setGeometry(QtCore.QRect(0, 0, 412, 31))
        self.label.setStyleSheet("background-color: rgb(0, 53, 81);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.LblJenisMsg = QtWidgets.QLabel(msgBox_ok)
        self.LblJenisMsg.setGeometry(QtCore.QRect(10, 5, 105, 21))
        font = QtGui.QFont()
        font.setFamily("Montaser Arabic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LblJenisMsg.setFont(font)
        self.LblJenisMsg.setStyleSheet("font-family:Montaser Arabic;\n"
"color:#ffffff;\n"
"font-weight: bold;\n"
"")
        self.LblJenisMsg.setObjectName("LblJenisMsg")
        self.LblKonten_isi = QtWidgets.QLabel(msgBox_ok)
        self.LblKonten_isi.setGeometry(QtCore.QRect(14, 38, 385, 120))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(15)
        self.LblKonten_isi.setFont(font)
        self.LblKonten_isi.setStyleSheet("color:#a6a6a6;")
        self.LblKonten_isi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.LblKonten_isi.setWordWrap(True)
        self.LblKonten_isi.setObjectName("LblKonten_isi")
        self.label_2 = QtWidgets.QLabel(msgBox_ok)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 412, 200))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.btnYa = QtWidgets.QPushButton(msgBox_ok)
        self.btnYa.setGeometry(QtCore.QRect(90, 181, 81, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnYa.setFont(font)
        self.btnYa.setStyleSheet("border: 1px solid #5ca3ff;\n"
"border-radius: 9px;\n"
"background-color: #5ca3ff;\n"
"color: #ffffff;")
        self.btnYa.setObjectName("btnYa")
        self.btnTidak = QtWidgets.QPushButton(msgBox_ok)
        self.btnTidak.setGeometry(QtCore.QRect(250, 181, 81, 26))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnTidak.setFont(font)
        self.btnTidak.setStyleSheet("border-radius: 9px;\n"
"background-color: #fd5d5d;\n"
"color: #ffffff;")
        self.btnTidak.setObjectName("btnTidak")
        self.label_2.raise_()
        self.label.raise_()
        self.LblJenisMsg.raise_()
        self.LblKonten_isi.raise_()
        self.btnYa.raise_()
        self.btnTidak.raise_()

        self.retranslateUi(msgBox_ok)
        QtCore.QMetaObject.connectSlotsByName(msgBox_ok)

    def retranslateUi(self, msgBox_ok):
        _translate = QtCore.QCoreApplication.translate
        self.LblJenisMsg.setText(_translate("msgBox_ok", "Konfirmasi"))
        self.LblKonten_isi.setText(_translate("msgBox_ok", "Apakah"))
        self.btnYa.setText(_translate("msgBox_ok", "Ya"))
        self.btnTidak.setText(_translate("msgBox_ok", "Tidak"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    msgBox_YaTdk = QtWidgets.QDialog()
    ui = Ui_msgBox_YaTdk()
    ui.setupUi(msgBox_YaTdk)
    msgBox_YaTdk.show()
    sys.exit(app.exec_())
