# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Loading_screen/form_loading_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_loading_screen(object):
    def setupUi(self, Form_loading_screen):
        Form_loading_screen.setObjectName("Form_loading_screen")
        Form_loading_screen.resize(892, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/LogoAndWindowsIcon/Aset/LogoIconSolusiku-final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_loading_screen.setWindowIcon(icon)
        Form_loading_screen.setStyleSheet("background-color: rgb(235, 235, 234);")
        self.label = QtWidgets.QLabel(Form_loading_screen)
        self.label.setGeometry(QtCore.QRect(0, 90, 892, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/Aset/Shadow_blue.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_loading_screen)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 892, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Images/Aset/shadowBlue_rotate.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_loading_screen)
        self.label_3.setGeometry(QtCore.QRect(328, 140, 243, 243))
        self.label_3.setStyleSheet("background-color:transparent;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Images/Aset/Icon-Solusiku-Splash.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form_loading_screen)
        QtCore.QMetaObject.connectSlotsByName(Form_loading_screen)

    def retranslateUi(self, Form_loading_screen):
        _translate = QtCore.QCoreApplication.translate
        Form_loading_screen.setWindowTitle(_translate("Form_loading_screen", "Loading ...."))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_loading_screen = QtWidgets.QWidget()
    ui = Ui_Form_loading_screen()
    ui.setupUi(Form_loading_screen)
    Form_loading_screen.show()
    sys.exit(app.exec_())
